version: "3.9"

services:
  database:
    image: cockroachdb/cockroach
    environment:
      COCKROACH_DATABASE: axeapi
      COCKROACH_USER: axeapi
      COCKROACH_ROOT_PASSWORD: 123456
    command: start-single-node --insecure
    ports:
      - "26257:26257"

  redis:
    image: redis:latest
    ports:
      - "6380:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
    ports:
      - "9201:9200"
      - "9301:9300"
