name: Create Tag

on:
  push:
    branches:
      - master
      - rc

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: butlerlogic/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.AUTO_TAG_TOKEN }}"
