name: Git Tag

on:
  push:
    branches:
      - master

jobs:
  tag-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install jq
        run: sudo apt-get install jq

      - name: Tag and push to GitHub
        continue-on-error: true
        run: |
          cd packages/axe-api
          echo ::set-output name=version::$(jq -r .version package.json)
          git config --local user.email "i.ozguradem@gmail.com"
          git config --local user.name "Özgür Adem Işıklı"
          git tag -a "v${{ steps.version.outputs.version }}" -m "Version ${{ steps.version.outputs.version }}"
          git push origin "v${{ steps.version.outputs.version }}"
