name: Depraveyard

on:
  push:
    branches:
      - develop

jobs:
  depraveyard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - run: npm ci
      - name: Depraveyard pushing
        run: npx depraveyard push --orgId ozziest-org-YLASRc --accessId ${{ secrets.DEPRAVEYARD_ACCESS_ID }} --accessToken ${{ secrets.DEPRAVEYARD_TOKEN }}