name: Partly Integration Tests

on:
  pull_request:
    branches:
      - develop
      - rc

jobs:
  rdbms:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
        database: ["mysql8", "mariadb", "postgres15", "cockroach"]
    env:
      TEST_USER: ${{ secrets.TEST_USER }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      TEST_DATABASE: ${{ secrets.TEST_DATABASE }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Install knex
        run: npm install -g knex
      - name: Testing all scenarions
        run: cd packages/integrations && sh ./run-tests.sh ${{ matrix.database }} 10

  sqlite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Install knex
        run: npm install -g knex
      - name: Testing all scenarions
        run: cd packages/integrations && sh ./run-tests.sh sqlite 5
