name: Integration Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        database: [mysql]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start database containers
        run: docker-compose -f "./tests/integrations/docker-compose.${{ matrix.database }}.yml" up -d --build
      - name: Install integration dependencies
        run: cd tests/integrations && npm install
      - run: npm ci
      - run: npm run build --if-present
      - name: Test all scenarions
        run: npm run test:integration:${{ matrix.database }}
