name: Tests

on:
  pull_request:
    branches:
      - master
      - develop
      - rc
jobs:
  units:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/axe-api
    strategy:
      matrix:
        node-version: [20.x, 22.x, 23.x, 24.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test

  linting:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/axe-api
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run lint
